(() => {
  'use strict';
  const clone=obj=>JSON.parse(JSON.stringify(obj));
  const defaults=clone(window.DARK_DATA||{}); let data=clone(defaults); let csrf='';
  const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const status=msg=>{const el=$('#savedStatus');if(el){el.textContent=msg;clearTimeout(status.t);status.t=setTimeout(()=>el.textContent='Ready',1800)}};
  let accessToken = sessionStorage.getItem('dark_admin_token') || '';
  async function api(action,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(accessToken)headers.Authorization=`Bearer ${accessToken}`;const r=await fetch(`/api?action=${encodeURIComponent(action)}`,{cache:'no-store',...options,headers});const j=await r.json().catch(()=>({ok:false,error:'Invalid server response'}));if(!r.ok||j.ok===false)throw new Error(j.error||`Request failed (${r.status})`);return j;}

  const field=(label,value,key,type='input',extra='')=>`<div class="field"><label>${esc(label)}</label>${type==='textarea'?`<textarea data-key="${esc(key)}" ${extra}>${esc(value)}</textarea>`:`<input data-key="${esc(key)}" value="${esc(value)}" ${extra}>`}</div>`;
  const wireInputs=root=>root.querySelectorAll('[data-key]').forEach(el=>el.addEventListener('input',()=>{const path=el.dataset.key.split('.');let ref=data;path.slice(0,-1).forEach(k=>ref=ref[k]);ref[path[path.length-1]]=el.value;}));
  async function save(){try{await api('save',{method:'POST',body:JSON.stringify({data})});status('Published ✓');}catch(e){status(e.message);alert(e.message)}}
  function renderGeneral(){ $('#general').innerHTML=`<div class="notice"><b>LIVE OWNER PANEL:</b> changes are saved directly to the server database and appear on the public website after refresh. No file export is required.</div><div class="card"><h2>Brand & Contact</h2><div class="grid2">${field('Brand name',data.brand,'brand')}${field('Founder name',data.founder,'founder')}${field('Email',data.email,'email')}${field('Phone',data.phone,'phone')}${field('Instagram URL',data.instagram,'instagram')}${field('Gmail URL',data.gmail,'gmail')}${field('WhatsApp URL',data.whatsapp,'whatsapp')}${field('Phone link',data.phoneLink,'phoneLink')}</div><div class="item-actions"><button class="btn primary" data-save>Save & Publish</button></div></div>`;wireInputs($('#general'));$('#general [data-save]').onclick=save; }
  function renderTestimonials(){ $('#testimonials').innerHTML=`<div class="card"><div class="row-head"><h2>Client Testimonials</h2><button class="btn" id="addTest">+ Add testimonial</button></div><div id="testList"></div><div class="item-actions"><button class="btn primary" data-save>Save & Publish</button></div></div>`;const list=$('#testList');data.testimonials.forEach((t,i)=>{const el=document.createElement('div');el.className='item';el.innerHTML=`<div class="grid2">${field('Client name',t.name,`testimonials.${i}.name`)}${field('Role / company',t.role,`testimonials.${i}.role`)}</div>${field('Testimonial',t.text,`testimonials.${i}.text`,'textarea')}<div class="item-actions"><button class="btn remove" data-remove="${i}">Remove</button></div>`;list.appendChild(el)});wireInputs($('#testimonials'));$('#testimonials [data-save]').onclick=save;$('#addTest').onclick=()=>{data.testimonials.push({text:'New client testimonial...',name:'Client Name',role:'Company / Role'});renderTestimonials();status('Added — click Save & Publish');};list.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{data.testimonials.splice(+b.dataset.remove,1);renderTestimonials();status('Removed — click Save & Publish');});}
  function renderProjects(){ $('#projects').innerHTML=`<div class="card"><div class="row-head"><h2>Recent Projects</h2><button class="btn" id="addProject">+ Add project</button></div><div id="projectList"></div><div class="item-actions"><button class="btn primary" data-save>Save & Publish</button></div></div>`;const list=$('#projectList');data.projects.forEach((p,i)=>{const el=document.createElement('div');el.className='item';el.innerHTML=`${field('Project title',p.title,`projects.${i}.title`)}<div class="grid2">${field('Category / tag',p.tag,`projects.${i}.tag`)}${field('Image URL',p.image,`projects.${i}.image`)}</div><div class="item-actions"><button class="btn remove" data-remove="${i}">Remove</button></div>`;list.appendChild(el)});wireInputs($('#projects'));$('#projects [data-save]').onclick=save;$('#addProject').onclick=()=>{data.projects.push({title:'New Project',tag:'WEB DESIGN',image:''});renderProjects();status('Added — click Save & Publish');};list.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{data.projects.splice(+b.dataset.remove,1);renderProjects();status('Removed — click Save & Publish');});}
  function renderServices(){ $('#services').innerHTML=`<div class="card"><div class="row-head"><h2>Services</h2><button class="btn" id="addService">+ Add service</button></div><div id="serviceList"></div><div class="item-actions"><button class="btn primary" data-save>Save & Publish</button></div></div>`;const list=$('#serviceList');data.services.forEach((s,i)=>{const el=document.createElement('div');el.className='item';el.innerHTML=`<div class="grid2">${field('Service title',s.title,`services.${i}.title`)}${field('Icon',s.icon,`services.${i}.icon`)}</div>${field('Description',s.text,`services.${i}.text`,'textarea')}${field('Image URL',s.image,`services.${i}.image`)}<div class="item-actions"><button class="btn remove" data-remove="${i}">Remove</button></div>`;list.appendChild(el)});wireInputs($('#services'));$('#services [data-save]').onclick=save;$('#addService').onclick=()=>{data.services.push({title:'New Service',text:'Describe this service here.',icon:'✦',image:''});renderServices();status('Added — click Save & Publish');};list.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{data.services.splice(+b.dataset.remove,1);renderServices();status('Removed — click Save & Publish');});}
  function renderTeam(){ $('#team').innerHTML=`<div class="card"><div class="row-head"><h2>Team Members</h2><button class="btn" id="addTeam">+ Add member</button></div><div id="teamList"></div><div class="item-actions"><button class="btn primary" data-save>Save & Publish</button></div></div>`;const list=$('#teamList');data.team.forEach((m,i)=>{const el=document.createElement('div');el.className='item';el.innerHTML=`<div class="grid2">${field('Name',m.name,`team.${i}.name`)}${field('Role',m.role,`team.${i}.role`)}</div>${field('Bio',m.bio,`team.${i}.bio`,'textarea')}${field('Image URL (optional)',m.image,`team.${i}.image`)}<div class="item-actions"><button class="btn remove" data-remove="${i}">Remove</button></div>`;list.appendChild(el)});wireInputs($('#team'));$('#team [data-save]').onclick=save;$('#addTeam').onclick=()=>{data.team.push({name:'New Member',role:'ROLE',bio:'Bio',image:''});renderTeam();status('Added — click Save & Publish');};list.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{data.team.splice(+b.dataset.remove,1);renderTeam();status('Removed — click Save & Publish');});}
  function renderAll(){renderGeneral();renderTestimonials();renderProjects();renderServices();renderTeam();}
  async function loadData(){const r=await api('site');if(r.data)data=r.data;}
  async function changePassword(){const next=prompt('New password (minimum 10 characters):');if(next===null)return;try{await api('password',{method:'POST',body:JSON.stringify({new_password:next})});alert('Password changed successfully.');}catch(e){alert(e.message)}}

  function showApp(username){$('#loginView').classList.remove('show');$('#appView').classList.add('show');$('#who').textContent=username;renderAll();}
  async function boot(){try{const s=await api('session');if(s.authenticated){await loadData();showApp(s.username);}else{$('#loginView').classList.add('show');}}catch(e){$('#loginError').textContent='Backend is not reachable or Vercel/Supabase is not configured yet.';$('#loginView').classList.add('show');}}
  $('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{const j=await api('login',{method:'POST',body:JSON.stringify({email:$('#username').value,password:$('#password').value})});accessToken=j.access_token;sessionStorage.setItem('dark_admin_token',accessToken);await loadData();showApp(j.username);}catch(err){$('#loginError').textContent=err.message;}};
  $('#logoutBtn').onclick=()=>{accessToken='';sessionStorage.removeItem('dark_admin_token');location.reload();};
  $('#passwordBtn').onclick=changePassword;
  document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$('#'+tab.dataset.tab).classList.add('active');$('#pageTitle').textContent=tab.textContent.replace(/^[^A-Za-z]+/,'').trim();});
  boot();
})();
